iStartWeb/Models/ErrorViewModel.cs
namespace iStartWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

iStartWeb/Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace iStartWeb.Models
{
    public class User
    {
        public Guid Id { get; set; }

        [MaxLength(75)]
        [MinLength(3)]
        [RegularExpression(@"^[a-zA-Z]*$", ErrorMessage = "Only alphabet characters are allowed.")]
        public string Name { get; set; }
        [EmailAddress]
        public string Email { get; set; }
        public string Gender { get; set; }
        [RegularExpression(@"^(?=.*[A-Z])(?=.*\d)(?=.*[^\w\s]).{8,12}$", ErrorMessage = "Must have 8 to 12 charecters and contains 1 uppercase, 1 special character, 1 numeric.")]
        public string Password { get; set; }
    }
}

iStartWeb/Controllers/iStartController.cs
using iStartWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using System.Text.Json.Serialization;

namespace iStartWeb.Controllers
{
    public class iStartController : Controller
    {
        Uri baseAddress = new Uri("https://localhost:7224/api");
        private readonly HttpClient _Client;

        public iStartController()
        {
            _Client = new HttpClient();
            _Client.BaseAddress = baseAddress;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(User user)
        {
            try
            {
                string data = JsonConvert.SerializeObject(user);
                StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
                HttpResponseMessage response = _Client.PostAsync(_Client.BaseAddress + "/User/SignIn", content).Result;

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("UsersDB");
                }
                
            }
            catch (Exception e)
            {
                return View();
            }

            return View();
        }

        public IActionResult UsersDB()
        {
            IEnumerable<User> userList = new List<User>();
            HttpResponseMessage response = _Client.GetAsync(_Client.BaseAddress + "/User/Get").Result;

            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                userList = JsonConvert.DeserializeObject<List<User>>(data);
            }
            return View(userList);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(User user)
        {
            try
            {
                string data = JsonConvert.SerializeObject(user);
                StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
                HttpResponseMessage response = _Client.PostAsync(_Client.BaseAddress + "/User/Post", content).Result;

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }catch(Exception e)
            {
                return View();
            }

            return View();
        }
    }
}

iStartWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - iStartWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/iStartWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.0/css/dataTables.dataTables.css" />

    <script>
        function validatePassword() {
            var password = document.getElementById("Password").value;
            var confirmPassword = document.getElementById("ConfirmPassword").value;

            if (password != confirmPassword) {
                document.getElementById("confirmPasswordError").innerHTML = "Passwords do not match";
                return false;
            } else {
                document.getElementById("confirmPasswordError").innerHTML = "";
                return true;
            }
        }
    </script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="iStart" asp-action="Index">iStartWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - iStartWeb 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/2.0.0/js/dataTables.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

iStartWeb/Views/iStart/Create.cshtml
@model User

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-uppercase text-center">Register</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 border-1 border">
            <form method="post" enctype="multipart/form-data" onsubmit="return validatePassword()">
                <div class="mb-3">
                    <label asp-for="@Model.Name" class="form-label"></label>
                    <input asp-for="@Model.Name" class="form-control" />
                    <span asp-validation-for="@Model.Name" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="@Model.Email" class="form-label"></label>
                    <input asp-for="@Model.Email" class="form-control" />
                    <span asp-validation-for="@Model.Email" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="@Model.Gender" ></label>
                    <select asp-for="@Model.Gender" class="form-control">
                        <option value="Male" >Male</option>
                        <option value="Female" >Female</option>
                    </select>
                    <span asp-validation-for="@Model.Gender" class="text-danger"></span>
                </div>
                
                <div class="mb-3">
                    <label asp-for="@Model.Password" class="form-label"></label>
                    <input asp-for="@Model.Password" class="form-control" type="password" id="Password" />
                    <span asp-validation-for="@Model.Password" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label">Re-enter Password</label>
                    <input class="form-control" type="password" id="ConfirmPassword"/>
                    <span id="confirmPasswordError" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <button type="submit" class="btn btn-success">Register</button>
                </div>
            </form>
        </div>

    </div>

</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

iStartWeb/Views/iStart/Index.cshtml
@model User

<div class="container">
    <div class="row">
        <div class="col-md-5">
            <h2 class="text-uppercase text-center">Sign In</h2>
        </div>
    </div>
    <div  class="col-md-5">
        <hr />
    </div>
    
    <div class="row">
        <div class="col-md-5">
            <form method="post" enctype="multipart/form-data" onsubmit="return validatePassword()">
                

                <div class="mb-3">
                    <label asp-for="@Model.Email" class="form-label"></label>
                    <input asp-for="@Model.Email" class="form-control" />
                </div>

                

                <div class="mb-3">
                    <label asp-for="@Model.Password" class="form-label"></label>
                    <input asp-for="@Model.Password" class="form-control" type="password" id="Password" />
                    
                </div>


                <div class="mb-3">
                   
                    <button type="submit" class="btn btn-primary">LOGIN</button>
                </div>
            </form>
            <br />
            <h5>Don't have an account? <a asp-controller="iStart" asp-action="Create" class="text-danger">Register</a></h5>


        </div>

    </div>

</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

iStartWeb/Views/iStart/UsersDB.cshtml
@model IEnumerable<User>

<div class="container">
    <div class="row mb-4">
        <div class="col-md-6 text-uppercase">
            <h1>User Management</h1>
        </div>
        <div class="col-md-6 text-end">
            <a asp-controller="iStart" asp-action="Create" class="btn btn-primary" style="color=pink"><i class="bi bi-plus"></i> New</a>
        </div>

    </div>
    <hr />

    @if (Model.Count() > 0)
    {
        <table id="table" class="table table-bordered table-striped">
            <thead>
                <tr>
              
                    <th>Name</th>
                    <th>Email</th>
                    <th>Edit</th>
                </tr>
            </thead>
            <tbody>
                
                @foreach (var user in Model)
                {
                 
                    <tr>
                        
                        <td>@user.Name</td>
                        <td>@user.Email</td>
                        <td class="d-flex align-items-center justify-content-center">
                            <div class="w-75 btn-group" role="group">
                                
                                <a asp-controller="iStart" asp-action="Edit" asp-route-id="@user.Id"
                                    data-toggle="tooltip" data-placement="top" title="Edit">
                                    <i class="bi bi-pencil-square"></i>
                                </a>
                                
                            </div>
                        </td>
                    </tr>
                }
            </tbody>

        </table>
    }
    else
    {
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="text-center text-uppercase text-warning pt-4">No Records to Show</h2>
                </div>
            </div>

        </div>
    }
</div>

@section Scripts{
    <script>
        $(".table").DataTable();
    </script>
}